[application]

# App (Project) Name
name = "prag-portal"

# Dioxus App Default Platform
# desktop, web
default_platform = "linux"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[bundle]
icon = [
    "icons/icon.png",
]
[web.app]

# HTML title tag content
title = "prag-portal"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
